directory: ".sushichan044"

tools:
  ghq:
    run: "ghq"
    env:
      GHQ_ROOT: "{{.ToolDir}}"
    description: "ghq wrapper with project-local configuration"

  memo:
    run: "memo"
    args:
      prepend:
        - new
    description: "Create project note file"
    env:
      MEMO_ROOT_DIR: "{{.ToolDir}}"

  dir:
    run: "{{.ConfigDir}}/tmpdir.sh"
    description: "Create a temporary directory in the project-local area"
    env:
      BASE_DIR: "{{.ToolDir}}"

aliases:
  gg:
    tool: ghq
    args:
      prepend:
        - get
        - -u
