shell = "zsh"

[plugins]

[plugins.zsh-defer]
github = 'romkatv/zsh-defer'
apply = ["source"]

[plugins.fast-syntax-highlighting]
github = 'zdharma-continuum/fast-syntax-highlighting'
apply = ["defer"]

[plugins.zsh-completions]
github = 'zsh-users/zsh-completions'
# do not apply defer or completions will not work

[plugins.zsh-autosuggestions]
github = 'zsh-users/zsh-autosuggestions'
use = ["{{ name }}.zsh"]
apply = ["defer"]

[plugins.powerlevel10k]
github = 'romkatv/powerlevel10k'
profiles = ["human"]

[plugins.zsh-256color]
github = 'chrissicool/zsh-256color'
apply = ["defer"]

[plugins.zsh-ssh]
github = 'sunlei/zsh-ssh'
apply = ["defer"]
profiles = ["human"]

[plugins.zsh-fzf-history-search]
github = 'joshskidmore/zsh-fzf-history-search'
apply = ["defer"]

[plugins.zsh-better-npm-completion]
github = 'lukechilds/zsh-better-npm-completion'
apply = ["defer"]

[templates]
defer = "{{ hooks?.pre | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks?.post | nl }}"
