#:schema https://mise.jdx.dev/schema/mise.json

[tools]
# When specifying multiple versions, dependabot will only update the first version.

# Languages
python = ["3.14.2", "3.12.10", "3.11.12"]
java = "25"
uv = "latest"
go = "1.25.5"
node = "25.2.1"
bun = "latest"
deno = "2.6.2"
tenv = "latest"
ruby = ["3.4.8", "3.3.10"]

# tools
awscli = "2.32.21"
watchexec = "latest"

# LSP
"github:withered-magic/starpls" = "latest"
"go:golang.org/x/tools/gopls" = "latest"
"npm:typescript-language-server" = "latest"
"npm:typescript" = "latest"
"npm:pyright" = "latest"

# AI tools
"github:openai/codex" = { version = "latest", bin = "codex" }
"npm:@ccusage/codex" = "latest"
"npm:@github/copilot" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:@modelcontextprotocol/inspector" = "latest"
"npm:ccusage" = "latest"
"npm:repomix" = "latest"


# tools with Backends
"cargo:cargo-binstall" = "latest"
"cargo:difftastic" = "latest"
"cargo:similarity-py" = "latest"
"cargo:similarity-rs" = "latest"
"cargo:similarity-ts" = "latest"
"go:github.com/bazelbuild/buildtools/buildifier" = "latest"
"go:github.com/bazelbuild/buildtools/buildozer" = "latest"
"go:github.com/bazelbuild/buildtools/unused_deps" = "latest"
"go:github.com/codesenberg/bombardier" = "latest"
"go:github.com/google/osv-scanner/v2/cmd/osv-scanner" = "latest"
"go:github.com/skanehira/rtty" = "latest"
"go:github.com/sushichan044/memo-cli/cmd/memo" = "latest"
"go:github.com/x-motemen/gore/cmd/gore" = "latest"
"go:github.com/ycd/dstp/cmd/dstp" = "latest"
"npm:@aku11i/phantom" = "latest"
"npm:@antfu/ni" = "latest"
"npm:@eslint/config-inspector" = "latest"
"npm:@getgrit/cli" = "latest"
"npm:@hono/cli" = "latest"
"npm:@napi-rs/cli" = "latest"
"npm:@typespec/compiler" = "latest"
"npm:ccsay" = "latest"
"npm:corepack" = { version = "latest", postinstall = "corepack enable && corepack disable pnpm" }
"npm:degit" = "latest"
"npm:difit" = "latest"
"npm:every-ts" = "latest"
"npm:git-cz" = "latest"
"npm:hereby" = "latest"
"npm:nrph" = "latest"
"npm:npkill" = "latest"
"npm:pnpm" = "latest"
"npm:pr-auto-ready" = "latest"
"npm:release-please" = "latest"
"npm:sfw" = "latest"
"npm:tsx" = "latest"
"pipx:markitdown" = { version = "latest", extras = "all", uvx_args = "-p 3.13" }
"pipx:yq" = "latest"
"pipx:docling" = "latest"
"pipx:plamo-translate" = { version = "latest", uvx_args = "-p 3.13", os = ["macos"]}

[tool_alias]
tenv = "asdf:https://github.com/tofuutils/asdf-tenv"

[settings]
experimental = true
idiomatic_version_file_enable_tools = [
    # see: https://github.com/jdx/mise/tree/866ae1ba0c9483357072541dd575203d5034c231/src/plugins/core and search for `idiomatic_file`
    "bun",
    "deno",
    "go",
    "java",
    "node",
    "python",
    "ruby",
    "rust",
    "swift",
    "terraform",
    "zig",
]
trusted_config_paths = [
    "~/workspace/github.com/sushichan044"
]

[settings.npm]
package_manager = "bun"

[settings.pipx]
uvx = true

[settings.python]
venv_stdlib = true
uv_venv_auto = true
